"""Render the build.yaml consumed by `ap gateway image build`."""

from __future__ import annotations

from typing import Any, Dict, List

import yaml

from .config import Config
from .resolver import ResolvedPolicy


def build_document(cfg: Config, policies: List[ResolvedPolicy]) -> Dict[str, Any]:
    return {
        "version": "v1",
        "gateway": {
            # `ap` tags the built images with gateway.version; it otherwise only uses it for default base
            # images, which are always set explicitly below. So this carries the output tag.
            "version": cfg.output_tag,
            "images": cfg.images(),
        },
        "policies": [p.build_entry() for p in sorted(policies, key=lambda p: p.name)],
    }


def render(cfg: Config, policies: List[ResolvedPolicy]) -> str:
    header = [
        "# Generated by aigw-builder - do not edit by hand.",
        f"# Config: derived from {cfg.from_image}" if cfg.from_image else f"# Config: {cfg.source}",
        f"# Image source: {cfg.image_source} (gateway {cfg.gateway_version}); output tag: {cfg.output_tag}",
        "# Resolved policies:",
    ]
    for p in sorted(policies, key=lambda p: p.name):
        header.append(f"#   {p.name:<45} {p.version or '-':<10} {p.kind:<7} ({p.origin})")
    body = yaml.safe_dump(build_document(cfg, policies), sort_keys=False, default_flow_style=False, width=1000)
    return "\n".join(header) + "\n" + body
